debug=true
logfile="/tmp/gggame.log"

[www]
port = 3000

[gpt]
instructions_file = "instructions.txt"
key_file="/home/smrt/.gptkey"
max_clients_count=10

[dirs]
pkg_www = "/home/smrt/w/gpt-game/server/www"
pkg_dist = "/home/smrt/w/gpt-game/frontend/dist"
pkg_assets = "/home/smrt/w/gpt-game/server/assets"