debug=true
root = "/gggame"

[www]
path = "/home/smrt/w/gpt-game/server/www"
port = 3000
frontend_path = "/home/smrt/w/gpt-game/frontend/dist"

[gpt]
path = "/home/smrt/w/gpt-game/server/assets"
instructions_file = "instructions.txt"
key_file="/home/smrt/.gptkey"
max_clients_count=10
