debug=true
root = "/gggame"
[www]

port = 3000
# path to server/www directory
path = "/home/smrt/w/gpt-game/server/www"
# path to wwweb dist directory
dist = "/home/smrt/w/gpt-game/frontend/dist"

[gpt]
# path to server assets directory
path = "/home/smrt/w/gpt-game/server/assets"
instructions_file = "instructions.txt"
key_file="/home/smrt/.gptkey"
max_clients_count=10
