[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]

thiserror = "2.0.16"
anyhow = "1.0.99"
serde_json = "1.0.143"
serde_with = "3.14.0"
chrono = "0.4.41"
serde = { version = "1.0", features = ["derive"] }
rand = "0.9.2"